import os
import sys
from dotenv import load_dotenv

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "../../..")))

from agentify.core import BaseAgent, AgentConfig
from agentify.memory import MemoryService
from agentify.memory.stores.in_memory_store import InMemoryStore
from agentify.multi_agent import Team
from agentify.extensions.tools import TimeTool, CalculatorTool

load_dotenv()


def create_planning_team():
    store = InMemoryStore()
    memory = MemoryService(store=store, log_enabled=True, max_log_length=200)

    # --- Worker 1: Infrastructure Researcher ---

    researcher_config = AgentConfig(
        name="InfraResearcher",
        system_prompt=(
            "You are a platform engineer who analyzes on-premise to cloud migration projects. "
            "- You identify technical and organizational risks. "
            "- You make approximate cost estimations (order of magnitude, not exact figures). "
            "- You can use calculation and current date tools to justify numbers and dates. "
            "- Your output should be structured and oriented to be consumed by another agent, not directly by management."
        ),
        provider="deepseek",
        model_name="deepseek-chat",
        temperature=0.1,
        max_tool_iter=10,
    )
    researcher = BaseAgent(
        config=researcher_config,
        memory=memory,
        tools=[CalculatorTool(), TimeTool()],
    )

    # --- Worker 2: Executive Writer ---

    writer_config = AgentConfig(
        name="ExecutiveWriter",
        system_prompt=(
            "You are a consultant who writes brief and clear executive summaries for management. "
            "- You receive technical notes and convert them into a report that is understandable for non-technical profiles. "
            "- Use simple language, structured in sections and with bullets when appropriate. "
            "- Keep the text to a maximum of ~300 words unless otherwise requested."
        ),
        provider="deepseek",
        model_name="deepseek-chat",
        temperature=0.4,
    )
    writer = BaseAgent(
        config=writer_config,
        memory=memory,
    )

    # --- Supervisor: Planner ---

    planner_config = AgentConfig(
        name="MigrationPlanner",
        system_prompt=(
            "You are the project manager for an on-premise to cloud system migration. "
            "- When the user makes a request, break down the problem into subtasks. "
            "- Use the researcher (InfraResearcher) to obtain risks, estimates, and technical details. "
            "- Use the writer (ExecutiveWriter) to transform everything into a final report for management. "
            "- Always honestly explain the assumptions behind the estimates. "
            "- Do not reveal to the user that you are delegating to other internal agents; "
            "just deliver a coherent final result."
        ),
        provider="deepseek",
        model_name="deepseek-chat",
        temperature=0.3,
    )
    planner = BaseAgent(
        config=planner_config,
        memory=memory,
    )

    team = Team(
        agents=[planner, researcher, writer],
        supervisor=planner,
    )

    return team


def main():
    print("Initializing project planning team...")
    team = create_planning_team()

    session_id = "migration_project_demo"

    query = (
        "I need a mini report (max 300 words) with the 3 main risks of migrating our on-premise "
        "databases to the cloud and an annual cost estimate for 5 TB of data. Include reasonable "
        "assumptions and reference to the type of costs (storage, transfer, operation, etc.)."
    )

    print("User:\n", query)
    response = team.run(
        user_input=query,
        session_id=session_id,
        user_id="cto_001",
    )
    print("\nReport generated by the team:\n")
    print(response)


if __name__ == "__main__":
    main()
